"""Build the word lists for Runes (public/runes/words.js).

Run by hand (not in CI) when the lists need changing:  python scripts/build_runes_words.py

Sources (both freely licensed):
- SCOWL by Kevin Atkinson, http://wordlist.aspell.net (see its Copyright file).
  Answers come from its common English + Australian word levels (10-35); proper names are
  in separate files and never used.
- ENABLE word list (public domain), only to widen the set of accepted guesses.
- Peter Norvig's word frequency counts (https://norvig.com/ngrams/) to order answers by
  how common they are.

Answers are shuffled with a fixed seed so the daily order never changes when this is re-run
with the same inputs. They're base64-encoded in the output only so nobody sees upcoming
answers by accident when viewing the page source.
"""
import base64
import glob
import io
import random
import re
import tarfile
import urllib.request
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "public" / "runes" / "words.js"
SCOWL_URL = "https://downloads.sourceforge.net/wordlist/scowl-2020.12.07.tar.gz"
ENABLE_URL = "https://raw.githubusercontent.com/dolph/dictionary/master/enable1.txt"
FREQ_URL = "https://norvig.com/ngrams/count_1w.txt"
BAD_URL = "https://raw.githubusercontent.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words/master/en"
MAX_ANSWERS = 2000

# Hand-picked removals: names/brands, web jargon, slang, plurals the filter misses, insults,
# crude or sensitive words, and Australian slang overseas players wouldn't know.
EXCLUDE = set("""
email click harry smith frank maria roman china bible kylie lilly sally dolly mason chuck trump
multi inter ultra gonna wanna kinda sorta dunno gimme lemme youse octal infix halon fiche unset
parse modal naked sperm booty spank lynch enema urine fetus vomit booze slave idiot moron bigot
sissy queer fatty obese booby bosom lusty thong chick daddy mamma bundy garbo pokie dunny doona
bogan galah shonk skite goodo razoo aftie enzed yakka bonze bonza sooky pilly smoko unman cooee
yabby chook kanga bluey nulla cuing eking aping acing axing ruing awing biffo unsay letup thous
pends shies plies dries flies fries cries spies ivies oases uteri genii radii cacti fungi taxis
kiwis delis menus gurus saris lymph karat gimme nappy hippy psych crack opium
""".split())


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": "fenrir-forge word list builder"})
    with urllib.request.urlopen(req, timeout=120) as r:
        return r.read()


def main():
    tar = tarfile.open(fileobj=io.BytesIO(fetch(SCOWL_URL)), mode="r:gz")
    scowl = {}
    for m in tar.getmembers():
        match = re.search(r"final/([a-z_0-9-]+)\.(\d+)$", m.name)
        if match:
            scowl[(match.group(1), int(match.group(2)))] = tar.extractfile(m).read().decode("latin-1").split()

    def words(cats, max_level, pattern):
        return {w for (c, lv), ws in scowl.items() if c in cats and lv <= max_level for w in ws if re.fullmatch(pattern, w)}

    common = words({"english-words", "australian-words"}, 35, r"[a-z]{5}")
    base = words({"english-words", "australian-words", "british-words", "american-words"}, 80, r"[a-z]+")
    accepted = words({"english-words", "australian-words", "british-words", "american-words", "canadian-words"}, 70, r"[a-z]{5}")
    accepted |= {w for w in fetch(ENABLE_URL).decode().split() if re.fullmatch(r"[a-z]{5}", w)}
    bad = set(fetch(BAD_URL).decode().lower().split())

    def inflected(w):
        """Plurals, past tenses and comparatives of shorter words (e.g. gawks, baked, wider)."""
        if w.endswith("s") and not w.endswith(("ss", "us", "is")) and (w[:-1] in base or (w.endswith("es") and w[:-2] in base)):
            return True
        if w.endswith("ed") and (w[:-2] in base or w[:-1] in base or (w[-3] == w[-4] and w[:-3] in base) or (w.endswith("ied") and w[:-3] + "y" in base)):
            return True
        if w.endswith(("er", "st")) and (w[:-2] in base or w[:-1] in base or (w.endswith(("ier", "iest")) and w[:-3] + "y" in base)):
            return True
        return False

    rank = {}
    for i, line in enumerate(fetch(FREQ_URL).decode().splitlines()):
        w = line.split("\t")[0]
        if len(w) == 5:
            rank.setdefault(w, i)

    answers = sorted((w for w in common if not inflected(w) and w not in bad and w not in EXCLUDE), key=lambda w: rank.get(w, 10**9))
    answers = answers[:MAX_ANSWERS]
    random.Random(20261007).shuffle(answers)
    accepted = sorted(accepted | set(answers))

    encoded = base64.b64encode("".join(answers).encode()).decode()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// Generated by scripts/build_runes_words.py from SCOWL (c) Kevin Atkinson and the public-domain\n"
        "// ENABLE list. Do not edit by hand.\n"
        f'const RUNES_ANSWERS = "{encoded}";\n'
        f'const RUNES_ACCEPTED = "{"".join(accepted)}";\n',
        encoding="utf-8",
    )
    print(f"{len(answers)} answers, {len(accepted)} accepted guesses -> {OUT}")


if __name__ == "__main__":
    main()
