"""Build the levels for Skald (public/skald/levels.js).

Run by hand:  python scripts/build_skald_levels.py

Each level is a wheel of letters (from one "seed" word) and every common word, 3+ letters long,
that can be made from them. Levels get harder in tiers: more letters and more words to find.
Uncommon words that can also be made are kept as "bonus words" (worth coins, not required).

Source: SCOWL by Kevin Atkinson (http://wordlist.aspell.net), freely licensed. Common words are
SCOWL levels 10-35; bonus words go up to level 50. Proper names and abbreviations are never used.
"""
import io
import json
import random
import re
import tarfile
import urllib.request
from collections import Counter
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "public" / "skald" / "levels.js"
SCOWL_URL = "https://downloads.sourceforge.net/wordlist/scowl-2020.12.07.tar.gz"
BAD_URL = "https://raw.githubusercontent.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words/master/en"

# (number of levels, seed word length, min words, max words)
TIERS = [
    (10, 4, 3, 4),
    (20, 5, 4, 6),
    (30, 5, 6, 9),
    (40, 6, 6, 10),
    (60, 6, 10, 14),
    (80, 7, 10, 15),
    (160, 7, 15, 22),
]

# Words that shouldn't be targets in a family game, on top of the public bad-words list.
EXCLUDE = set("""
nazi nazis rape raped rapes rapist slut sluts whore whores porn porno sexy sex sexes pimp pimps
pee pees poo poos piss bum bums tit tits arse arses fag fags gay gays homo nigger negro wank
drug drugs kill kills killed bomb bombs suicide onya arvo arvos smoko yakka
""".split())


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": "fenrir-forge level builder"})
    with urllib.request.urlopen(req, timeout=120) as r:
        return r.read()


def main():
    tar = tarfile.open(fileobj=io.BytesIO(fetch(SCOWL_URL)), mode="r:gz")
    lists = {}
    for m in tar.getmembers():
        match = re.search(r"final/([a-z_0-9-]+)\.(\d+)$", m.name)
        if match:
            lists[(match.group(1), int(match.group(2)))] = tar.extractfile(m).read().decode("latin-1").split()

    def words(cats, max_level):
        return {w for (c, lv), ws in lists.items() if c in cats and lv <= max_level for w in ws if re.fullmatch(r"[a-z]{3,7}", w)}

    blocked = set(fetch(BAD_URL).decode().lower().split()) | EXCLUDE
    common = words({"english-words", "australian-words"}, 35) - blocked
    wide = words({"english-words", "australian-words", "british-words", "american-words"}, 50) - blocked

    def formable(word, letters):
        return all(letters[ch] >= n for ch, n in Counter(word).items())

    rng = random.Random(20261007)
    used_seeds, used_sets, levels = set(), set(), []
    for count, length, lo, hi in TIERS:
        seeds = sorted(w for w in common if len(w) == length)
        rng.shuffle(seeds)
        made = 0
        for seed in seeds:
            letters = Counter(seed)
            key = "".join(sorted(seed))
            if seed in used_seeds or key in used_sets:
                continue
            targets = sorted((w for w in common if len(w) <= length and formable(w, letters)), key=lambda w: (len(w), w))
            if not lo <= len(targets) <= hi:
                continue
            bonus = sorted(w for w in wide if len(w) <= length and formable(w, letters) and w not in targets)
            wheel = list(seed)
            while "".join(wheel) == seed:
                rng.shuffle(wheel)
            levels.append(["".join(wheel), targets, bonus[:40]])
            used_seeds.add(seed)
            used_sets.add(key)
            made += 1
            if made == count:
                break
        if made < count:
            raise SystemExit(f"Only found {made} of {count} levels for tier {length} letters, {lo}-{hi} words")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// Generated by scripts/build_skald_levels.py from SCOWL (c) Kevin Atkinson. Do not edit by hand.\n"
        "// Each level: [wheel letters, words to find, bonus words]\n"
        "const SKALD_LEVELS = " + json.dumps(levels, separators=(",", ":")) + ";\n",
        encoding="utf-8",
    )
    print(f"{len(levels)} levels -> {OUT}")
    for i in (0, 9, 10, 30, 60, 100, 160, 240, 399):
        print(f"  level {i + 1}: {levels[i][0]} -> {' '.join(levels[i][1])}  (+{len(levels[i][2])} bonus)")


if __name__ == "__main__":
    main()
